export const ACTION_SIGN_IN = 'sign_in';
export const ACTION_SIGN_UP = 'sign_up';
export const ACTION_LOG_OUT = 'log_out';
export const ACTION_UPDATE_PROFILE = 'update_profile';
export const ACTION_FETCH_DATA = 'fetch_data';
export const ACTION_CONTACT_US = 'contact_us';
export const ACTION_DONATE = 'donate'; /*donate form submit*/
export const ACTION_REQUEST = 'request'; /*request form submit*/
export const ACTION_CONFIRM_APPOINTMENT = 'confirm_appointment';
export const ACTION_REQUEST_PLASMA = 'request_plasma';
export const ACTION_REQUEST_BLOOD = 'request_blood';
export const ACTION_REQUEST_REDCELLS = 'request_redcells';
export const ACTION_REQUEST_PLatelets = 'request_platelets';
export const ACTION_DONATION_PLASMA = 'donation_plasma';
export const ACTION_DONATION_BLOOD = 'donation_blood';
export const ACTION_DONATION_REDCELLS = 'donation_redcells';
export const ACTION_DONATION_PLatelets = 'donation_platelets';
export const ACTION_TRANSLATE = 'translate';
